export default
{
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',

    ADD_PROCEDURE: 'ADD_PROCEDURE',
    REMOVE_PROCEDURE: 'REMOVE_PROCEDURE',
    ADD_PROFESSIONAL: 'ADD_PROFESSIONAL',
    REMOVE_PROFESSIONAL: 'REMOVE_PROFESSIONAL',
    RESET_ESTABLISHMENT: 'RESET_ESTABLISHIMENT',
    CREATE_ESTABLISHMENT: 'CREATE_ESTABLISHMENT',

    GET_PACIENT_APPOINTMENTS: 'GET_PACIENT_APPOINTMENTS',
    GET_PROFESSIONAL_APPOINTMENTS: 'GET_PROFESSIONAL_APPOINTMENTS',
    GET_ESTABLISHMENT_APPOINTMENTS: 'GET_ESTABLISHMENT_APPOINTMENTS',
    CONFIRM_PROFESSIONAL: 'CONFIRM_PROFESSIONAL',
    GET_ESTABLISHMENTS: 'GET_ESTABLISHMENTS',
    GET_PROCEDURES: 'GET_PROCEDURES',
    GET_PROFESSIONALS: 'GET_PROFESSIONALS',
    SCHEDULE_APPOINTMENT: 'SCHEDULE_APPOINTMENT',

    ADD_ESTABLISHMENT_TO_REPORT: 'ADD_ESTABLISHMENT_TO_REPORT',
    REMOVE_ESTABLISHMENT_FROM_REPORT: 'REMOVE_ESTABLISHMENT_FROM_REPORT',
    ADD_PROCEDURE_TO_REPORT: 'ADD_PROCEDURE_TO_REPORT',
    REMOVE_PROCEDURE_FROM_REPORT: 'REMOVE_PROCEDURE_FROM_REPORT',
    GENERATE_REPORT: 'GENERATE_REPORT'
}